### ISSUE TITLE
crash: SOLVER ERROR

### ISSUE THREAD

**Issue by kostis** [aggelgian/cuter#25]
I get the following crash  -- the `cd` command refers to the dir where Erlang/OTP resides:
```
$ cd otp/lib/hipe/ebin
$ cuter hipe_icode_primops pp '[standard_io, 42]'
Testing hipe_icode_primops:pp/2 ...
  ...
xxxxx[SOLVER ERROR] {"python -u /home/kostis/HiPE/cuter/priv/cuter_interface.py",
                [{{'__s',"0.0.16.103"},standard_io},
                 {{'__s',"0.0.16.104"},{apply_N,0}}],
                "/home/kostis/HiPE/otp/lib/hipe/ebin/temp/execexec6/run.trace",
                12}
Proccess <0.35.0> exited with {{solving,
                                   {unexpected_info,
                                       {'EXIT',#Port<0.1524>,normal}}},
                               {gen_fsm,sync_send_event,
                                   [<0.208.0>,check_model,500000]}}
```

**Comment by aggelgian** [comment]
The problem lies in the fact that the solver doesn't recognize PIDs and references.

In the current implementation, CutEr will record these datatypes in the trace file during an execution.
For example, one entry in the trace file is
```
$23 = { io_request, <0.63.0>, #Ref<0.0.4.544>, $22 }
```
When the solver component tries to load this entry, it fails as the PID and the reference are of unknown types.

Since, our solver cannot reason about these things and their values is execution specific, i'll replace them during trace loading with a default value, let's say `42`.
